services:
  config-server:
    image: petclinic/config-server:${TAG:-dev}
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: "git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/JerryGao0805/petclinic-ms-from-scratch-config.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: "main"
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8888/actuator/health/readiness >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  discovery-server:
    image: petclinic/discovery-server:${TAG:-dev}
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8761/actuator/health/readiness >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  customers-service:
    image: petclinic/customers-service:${TAG:-dev}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8081/actuator/health/readiness >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s


  vets-service:
    image: petclinic/vets-service:${TAG:-dev}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8082/actuator/health/readiness >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  visits-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${VISITS_DB_NAME}
      POSTGRES_USER: ${VISITS_DB_USER}
      POSTGRES_PASSWORD: ${VISITS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - visits-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U visits -d visits -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s


  visits-service:
    image: petclinic/visits-service:${TAG:-dev}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      visits-db:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      SPRING_DATASOURCE_URL: jdbc:postgresql://visits-db:5432/${VISITS_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${VISITS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${VISITS_DB_PASSWORD}

    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8083/actuator/health/readiness >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

  api-gateway:
    image: petclinic/api-gateway:${TAG:-dev}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      customers-service:
        condition: service_healthy
      vets-service:
        condition: service_healthy
      visits-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CONFIG_IMPORT: "configserver:"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health/readiness >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 30s

volumes:
  visits-db-data: