name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Ensure mvnw executable
        run: chmod +x mvnw

      - name: Run tests (all modules)
        run: ./mvnw -ntp -B test

      - name: Package jars (skip tests)
        run: ./mvnw -ntp -B -DskipTests package

      - name: Docker build (all services)
        run: make docker-build TAG=ci

      - name: Docker compose up (all service)
        run:
          make up TAG=ci
      - name: Docker compose verify (all service)
        run:
          make verify