CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    visit_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE INDEX idx_visits_pet_id ON visits(pet_id);